version: "3"
services:
  app:
    image: node-typescript
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_HOST=app
      - PORT=80
    ports:
      - "3000:80"
    volumes:
      - .:/app
    