services:
  authorizor:
    container_name: authorizor
    image: node-typescript
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_HOST=authorizor
      - PORT=80
    env_file: .env
    ports:
      - "3001:80"
    volumes:
      # - .:/app
      - ./src:/app/src
      - ./__tests__:/app/__tests__
    entrypoint: ["npm", "run", "dev"]
